const bodyList = (bodyType: BodyPartConstant, bodyCount: number) => Array.from({ length: bodyCount }, () => bodyType)
export const CreepRoleConfig: CreepRole = {
    /* 基本房间运营 */
    harvester: { roleCode: 'H', warMode: false, priority: 1 },
    upgrader: { roleCode: "U", warMode: false, priority: 3 },
    builder: { roleCode: "B", warMode: false, priority: 2 },
    repairer: { roleCode: "R", warMode: false, priority: 4 },
    filler: { roleCode: "F", warMode: false, priority: 2 },
    miner: { roleCode: "M", warMode: false, priority: 0 },
    scout: { roleCode: "S", warMode: false, priority: 0 },
    manager: { roleCode: "C", warMode: false, priority: 0 },
    processer: { roleCode: "P", warMode: false, priority: 0 },
    claimer: { roleCode: "CL", warMode: false, priority: 0 },
    reserver: { roleCode: "RE", warMode: false, priority: 0 },
    rHarvester: { roleCode: "RH", warMode: false, priority: 0 },
    rFiller: { roleCode: "RF", warMode: false, priority: 0 },
    rBuilder: { roleCode: "RB", warMode: false, priority: 0 },
    attacker: { roleCode: "ATT", warMode: false, priority: 0 },
    healer: { roleCode: "HEA", warMode: false, priority: 0 },
    rAttacker: { roleCode: "", warMode: false, priority: 0 },
    dismantler: { roleCode: "", warMode: false, priority: 0 },
    integrate: { roleCode: "", warMode: false, priority: 0 },
    defender: { roleCode: "", warMode: false, priority: 0 },
    rdefender: { roleCode: "", warMode: false, priority: 0 },
    cAttacker: { roleCode: "", warMode: false, priority: 0 },
}