// 合成需求配置
export const reactionConfig = {
    [RESOURCE_HYDROXIDE]: 10000,

    [RESOURCE_ZYNTHIUM_KEANITE]: 10000,
    [RESOURCE_UTRIUM_LEMERGITE]: 10000,
    [RESOURCE_GHODIUM]: 10000,                      // Nuker    !!!

    [RESOURCE_CATALYZED_LEMERGIUM_ACID]: 30000,     // +100% repair 和 build 效率但不增加其能量消耗
    [RESOURCE_LEMERGIUM_ACID]: 10000,               // +80% repair 和 build 效率但不增加其能量消耗
    [RESOURCE_LEMERGIUM_HYDRIDE]: 10000,            // +50% repair 和 build 效率但不增加其能量消耗

    [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: 10000,      // +300% dismantle 效率
    [RESOURCE_ZYNTHIUM_ACID]: 10000,                // +200% dismantle 效率
    [RESOURCE_ZYNTHIUM_HYDRIDE]: 10000,             // +100% dismantle 效率

    [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: 10000,  // +300% fatigue(疲劳值) 减低速度
    [RESOURCE_ZYNTHIUM_ALKALIDE]: 10000,            // +200% fatigue(疲劳值) 减低速度
    [RESOURCE_ZYNTHIUM_OXIDE]: 10000,               // +100% fatigue(疲劳值) 减低速度

    [RESOURCE_CATALYZED_GHODIUM_ACID]: 10000,       // +100% upgradeController 效率但不增加其能量消耗
    [RESOURCE_GHODIUM_ACID]: 10000,                 // +80% upgradeController 效率但不增加其能量消耗
    [RESOURCE_GHODIUM_HYDRIDE]: 10000,              // +50% upgradeController 效率但不增加其能量消耗

    [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: 10000,   // 70% 伤害减免
    [RESOURCE_GHODIUM_ALKALIDE]: 10000,             // 50% 伤害减免
    [RESOURCE_GHODIUM_OXIDE]: 10000,                // 30% 伤害减免

    [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: 10000, // +300% heal and rangedHeal 效率
    [RESOURCE_LEMERGIUM_ALKALIDE]: 10000,           // +200% heal 和 rangedHeal 效率
    [RESOURCE_LEMERGIUM_OXIDE]: 10000,              // +100% heal 和 rangedHeal 效率

    [RESOURCE_CATALYZED_KEANIUM_ACID]: 10000,       // +150 容量
    [RESOURCE_KEANIUM_ACID]: 10000,                 // +100 容量
    [RESOURCE_KEANIUM_HYDRIDE]: 10000,              // +50 容量

    [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: 10000,   // +300% rangedAttack 和 rangedMassAttack 效率
    [RESOURCE_KEANIUM_ALKALIDE]: 10000,             // +200% rangedAttack 和 rangedMassAttack 效率
    [RESOURCE_KEANIUM_OXIDE]: 10000,                // +100% rangedAttack 和 rangedMassAttack 效率

    [RESOURCE_CATALYZED_UTRIUM_ACID]: 10000,        // +300% attack 效率
    [RESOURCE_UTRIUM_ACID]: 10000,                  // +200% attack 效率
    [RESOURCE_UTRIUM_HYDRIDE]: 10000,               // +100% attack 效率

    [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: 10000,    // +600% harvest 效率
    [RESOURCE_UTRIUM_ALKALIDE]: 10000,              // +400% harvest 效率
    [RESOURCE_UTRIUM_OXIDE]: 10000,                 // +200% harvest 效率
}

// 从反应目标产物获取其底物的对应表
export const reactionSource: IReactionSource = {
    // 三级化合物
    [RESOURCE_CATALYZED_GHODIUM_ACID]: [RESOURCE_GHODIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ACID]: [RESOURCE_KEANIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_UTRIUM_ACID]: [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_ALKALIDE, RESOURCE_CATALYST],
    // 二级化合物
    [RESOURCE_GHODIUM_ACID]: [RESOURCE_GHODIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ACID]: [RESOURCE_KEANIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_UTRIUM_ACID]: [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_OXIDE, RESOURCE_HYDROXIDE],
    // 一级化合物
    [RESOURCE_GHODIUM_HYDRIDE]: [RESOURCE_GHODIUM, RESOURCE_HYDROGEN],
    [RESOURCE_GHODIUM_OXIDE]: [RESOURCE_GHODIUM, RESOURCE_OXYGEN],
    [RESOURCE_KEANIUM_HYDRIDE]: [RESOURCE_KEANIUM, RESOURCE_HYDROGEN],
    [RESOURCE_KEANIUM_OXIDE]: [RESOURCE_KEANIUM, RESOURCE_OXYGEN],
    [RESOURCE_LEMERGIUM_HYDRIDE]: [RESOURCE_LEMERGIUM, RESOURCE_HYDROGEN],
    [RESOURCE_LEMERGIUM_OXIDE]: [RESOURCE_LEMERGIUM, RESOURCE_OXYGEN],
    [RESOURCE_UTRIUM_HYDRIDE]: [RESOURCE_UTRIUM, RESOURCE_HYDROGEN],
    [RESOURCE_UTRIUM_OXIDE]: [RESOURCE_UTRIUM, RESOURCE_OXYGEN],
    [RESOURCE_ZYNTHIUM_HYDRIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_HYDROGEN],
    [RESOURCE_ZYNTHIUM_OXIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_OXYGEN],
    [RESOURCE_GHODIUM]: [RESOURCE_ZYNTHIUM_KEANITE, RESOURCE_UTRIUM_LEMERGITE],
    // 基础化合物
    [RESOURCE_ZYNTHIUM_KEANITE]: [RESOURCE_ZYNTHIUM, RESOURCE_KEANIUM],
    [RESOURCE_UTRIUM_LEMERGITE]: [RESOURCE_UTRIUM, RESOURCE_LEMERGIUM],
    [RESOURCE_HYDROXIDE]: [RESOURCE_HYDROGEN, RESOURCE_OXYGEN],
}
